import React from "react";
import type { NextPage } from 'next'
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Layout from "@components/Layout";

const Home: NextPage = () => {
    return (
        <>
            <Layout>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <section className="text-gray-600 body-font">
                    <div className="max-w-7xl mx-auto lg:flex px-5 pt-10 pb-20 content-center items-center">
                        <div className="lg:w-5/6  md:ml-24 pt-6 flex flex-col md:items-start lg:text-left items-center text-center">
                            <h1 className="mb-5 sm:text-6xl font-bold text-5xl items-center Avenir lg:w-3/4 xl:w-2/2 text-gray-900">
                                We are making Stunning Websites
                            </h1>
                            <p className="mb-4 lg:w-2/2 text-gray-600 text-lg lg:text-left text-center">
                                nine4 is a free to use website template for websites made with
                                Next.js and styled with Tailwind CSS
                            </p>
                            <div className="flex justify-center sm:m-auto md:ml-0">
                                <Link href="/"
                                    className="inline-flex items-center px-5 py-3 mt-2 font-medium text-white transition duration-500 ease-in-out border rounded-lg bg-gray-800 hover:bg-gray-900"
                                >
                                    <span className="justify-center">Find out more</span>

                                </Link>
                            </div>
                        </div>
                        <div className="w-2/4 mb-0 lg:mb-0 md:pl-10 m-auto">
                            <Image
                                className="w-80 md:ml-1 ml-24"
                                alt="iPhone-12"
                                src="/images/iPhone-12-Mockup.png"
                                width={100} height={100} objectFit="contain"
                            />
                        </div>
                    </div>
                    <section className="mx-auto">
                        <div className="container px-5 mx-auto lg:px-24 ">
                            <div className="flex flex-col w-full mb-4 text-left lg:text-center">
                                <h1 className="mb-8 text-2xl Avenir font-semibold text-black">
                                    Trusted by top-tier product companies
                                </h1>
                            </div>
                            <div className="grid grid-cols-2 gap-16 mb-16 text-center lg:grid-cols-4">
                                <div className="flex items-center justify-center">
                                    <Image
                                        src="/images/Google-Logo.webp"
                                        alt="Google Logo"
                                        className="block object-contain h-16 greyC"
                                        width={100} height={100} objectFit="contain"
                                    />
                                </div>
                                <div className="flex items-center justify-center">
                                    {/* <div
                                        style={{
                                            position: "relative",
                                            width: "100%",
                                            height: "100px",
                                            maxHeight: "100px",
                                            maxWidth: "100%",
                                        }}
                                    > */}
                                    <Image
                                        src="/images/Shopify-Logo.svg"
                                        alt="Shopify Logo"
                                        className="block object-contain h-16 greyC"
                                        width={100} height={100} objectFit="contain"
                                    />
                                    {/* </div> */}
                                </div>
                                <div className="flex items-center justify-center">
                                    <Image
                                        src="/images/Cloudflare-Logo.svg"
                                        alt="Cloudflare Logo"
                                        className="block object-contain h-16 greyC"
                                        width={100} height={100} objectFit="contain"
                                    />
                                </div>
                                <div className="flex items-center justify-center">
                                    <Image
                                        src="/images/PayPal-Logo.png"
                                        alt="Paypal Logo"
                                        className="block object-contain h-16 greyC"
                                        width={100} height={100} objectFit="contain"
                                    />
                                </div>
                            </div>
                        </div>
                    </section>
                    <div className="grr max-w-7xl pt-20 mx-auto text-center">
                        <h1 className="mb-8 text-6xl Avenir font-semibold text-gray-900">
                            Less code, less effort.
                        </h1>
                        <h1 className="mb-8 text-2xl Avenir font-semibold text-gray-600 text-center">
                            Minify your CSS with Tailwinds built in PostCSS support.
                        </h1>
                        <div className="container flex flex-col items-center justify-center mx-auto rounded-lg">

                            <Image
                                className="w-80 md:ml-1 ml-24"
                                alt="Placeholder Image"
                                src="/images/placeholder.png"
                                width={100} height={100} objectFit="contain"
                            />
                        </div>
                    </div>
                    <section className="relative">
                        <div className="max-w-6xl mx-auto px-4 sm:px-6 text-center">
                            <div className="py-24 md:py-36">
                                <h1 className="mb-5 text-6xl Avenir font-semibold text-gray-900">
                                    Subscribe to our newsletter
                                </h1>
                                <h1 className="mb-9 text-2xl font-semibold text-gray-600">
                                    Enter your email address and get our newsletters straight away.
                                </h1>
                                <input
                                    placeholder="jack@example.com"
                                    name="email"
                                    type="email"
                                    autoComplete="email"
                                    className="border border-gray-600 w-1/4 pr-2 pl-2 py-3 mt-2 rounded-md text-gray-800 font-semibold hover:border-gray-900"
                                ></input>
                                <Link href="/"
                                    className="inline-flex items-center px-14 py-3 mt-2 ml-2 font-medium text-white ease-in-out border rounded-lg bg-gray-800 hover:bg-gray-900"
                                >
                                    <span className="justify-center">Subscribe</span>
                                </Link>
                            </div>
                        </div>
                    </section>
                </section>
            </Layout>
        </>
    )
}

export default Home
